language: java
notifications:
    email: false
    ignore:
      - *.md
      - lab01/src/test/java/pl/pawellakomiec/domain/SiteTest.java
install: true
before_script:
- cd scripts; ./server.sh &
script:
- sleep 1
- cd ..; mvn test